### ISSUE TITLE
Is this compatible with browsers?

### ISSUE THREAD

**Issue by bababoyy** [danik4985/sus#5]
It'd be epic if it is

**Comment by danik4985** [comment]
From what I've tested it is. If you find any browser issues let me know.

**Comment by danik4985** [comment]
Tho I think you might have to manually put "localStorage" and "window" and "document" and maybe other web things I forgot to the ignore array.

**Comment by danik4985** [comment]
ok i just realised it will try to rename "require" so ima add a web mode that fixes that rq

**Comment by danik4985** [comment]
yup I fixed it and added webMode (see README.md)
sorry for my chaoticness btw
